name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        run: npm install --global pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build current repository
        run: pnpm build
      - name: Package current repository
        run: pnpm package
      - name: Setup R2-Explorer
        env:
          R2EXPLORER_WORKER_NAME: ${{ vars.R2EXPLORER_WORKER_NAME }}
          R2EXPLORER_CONFIG: ${{ secrets.R2EXPLORER_CONFIG }}
          R2EXPLORER_BUCKETS: ${{ vars.R2EXPLORER_BUCKETS }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: node packages/github-action/prepareDeploy.js
      - name: Install current R2-Explorer package
        working-directory: packages/github-action
        run: |
          npm install
          npm install --save ../worker/r2-explorer-*.tgz
      - name: Deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "packages/github-action"
          wranglerVersion: "4.86.0"
